name = "football-worker"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
WORKER_BASE_URL = "https://football-worker.mahdijadir38.workers.dev"

[[kv_namespaces]]
binding = "FOOTBALL_KV"
id = "17992c17e0c8485cb2098808c7336d9b"

[triggers]
crons = [
  "* * * * *",
  "0 */6 * * *",
  "*/20 * * * *"
]
